documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.{html,md,txt}'
i18n:
  - changed-files:
      - any-glob-to-any-file: '**/assets/*/lang/*'
assets:
  - all:
      - changed-files:
          - any-glob-to-any-file: '**/assets/**/*'
          - all-globs-to-all-files: '!**/assets/*/lang/*'
ci:
  - changed-files:
      - any-glob-to-any-file: ['.releaserc*', '.github/**/*']
build:
  - changed-files:
      - any-glob-to-any-file: ['**/build.gradle', '**/gradle.properties', '**/settings.gradle']
